# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceOrdering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oredem_de_servico',
            name='aberta',
            field=models.BooleanField(default=False),
        ),
    ]
