# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceOrdering', '0002_oredem_de_servico_aberta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oredem_de_Servico',
            new_name='Ordem_de_Servico',
        ),
    ]
